version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
  e2e-test:
    docker:
      - image: saucelabs/storybook-base
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install --prefix tests/e2e
      - run: npm run storybook:build --prefix tests/e2e
      - run: npm test:e2e --prefix tests/e2e

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - e2e-test
