version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  e2e-test:
    docker:
      - image: saucelabs/storybook-base:alpha-rc.0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - e2e-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - e2e-dependencies-
      - run: npm install
      - run: npm install --prefix test/e2e
      - save_cache:
          paths:
            - node_modules
          key: e2e-dependencies-{{ checksum "package.json" }}
      - run: npm run storybook:build --prefix test/e2e
      - run: npm run storybook:test-static --prefix test/e2e

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - e2e-test
